from functions import curtir_todas_musicas_playlist, extract_spotify_playlist_id, verificar_status_curtidas_playlist


verificar_status_curtidas_playlist(extract_spotify_playlist_id("https://open.spotify.com/playlist/0LKBRxRuLiYpqBsfZ6jRJ2?si=5c846bcc3bdb46d6"))
